import { NextRequest, NextResponse } from 'next/server';
import { personas, getPersonaBySlug } from '@/lib/personas';

const SAMPLE_SCRIPTS = [
  `========================================

HOST: Darth Vader
"I find your lack of faith disturbing. And your lack of comedy talent is even more disturbing."

ROASTER 1: Hulk Hogan
"Whoooo brother! Let me tell you something, you absolute jabroni -"
"I've been to infinity and beyond, and I've never seen someone choke under pressure quite like you!"
"You call that a roast? I've seen kindergartners roast harder at show and tell!"

ROASTER 2: SpongeBob
"I'm ready! I'm ready! I'm ready to roast you!"
"Bikini Bottom would never accept someone as uncool as you!"
"You know what they say about people who can't take a joke? They probably live in a pineapple under the sea. WAIT THAT'S ME!"

ROASTEE: Ric Flair
"WOOOOOOO! You think you can just come in here and roast the Nature Boy?!"
"I've been wrestling for 40 years and I've NEVER seen such a mediocre performance!"
"I once dated more famous women than you have followers on social media!"

========================================

Generated by Humble Claw Roast Generator`,

  `========================================

HOST: Arnold Schwarzenegger
"I am the governator of this roast. And you... you are terminated."

ROASTER 1: Mike Tyson
"Everyone has a plan until they get punched in the mouth - and your plan is garbage."
"You talk a lot of trash for someone with no reach and no chin."
"I once bit a man's ear off. You've got less knockout power than my vegetarian breakfast."

ROASTER 2: Macho Man Randy Savage
"Oh yeah! You're absolutely terrible at this!"
"I'm the cream of the crop and you're just milk leftovers!"
"There's only one Macho Man in this ring, and you're just a cheap imitation!"

ROASTEE: The Undertaker
"..."
*long creepy pause*
"Your career is about to rest... in peace."
"I've killed more careers than the reaper himself. And I AM the reaper."
"You should have stayed buried."

========================================

Generated by Humble Claw Roast Generator`,

  `========================================

HOST: Ric Flair
"WOOOOOO! Welcome to the biggest roast session in the universe!"

ROASTER 1: Keanu Reeves
"Whoa... I've been in more action movies than you've had hot meals."
"I outran everything from The Matrix to a slow news day. You couldn't outrun your own bad decisions."
*said softly* "I don't mean to be mean... but you're really bad at this."

ROASTER 2: Peter Griffin
"Uhhh... your brain's so slow it makes Quagmire look like Einstein."
"I'd roast you but my brain don't work that good."
"You got less coordination than a drunk Lois trying to parallel park."

ROASTEE: SpongeBob
"I'm ready! I'm ready! I'm ready!"
"Gary? Is this person being mean to me? Meow."
"Bikini Bottom says NO to your mediocre roast skills!"

========================================

Generated by Humble Claw Roast Generator`,
];

export async function POST(request: NextRequest) {
  try {
    const { host, roasters, roastee, profanity } = await request.json();
    
    // Check for OpenAI API key
    const apiKey = process.env.OPENAI_API_KEY;
    
    if (apiKey) {
      // Use real OpenAI API
      const hostPersona = getPersonaBySlug(host);
      const roasteePersona = getPersonaBySlug(roastee);
      const roasterPersonas = roasters.map((slug: string) => getPersonaBySlug(slug)).filter(Boolean) as Array<{name?: string; voice?: string; roastStyle?: string}>;
      
      const profanityInstructions = [
        'Kid-friendly. No swears. No adult references. Clean comedy only.',
        'Light teasing. No swears. Mild innuendo allowed.',
        'Moderate burns. Mild language. Some adult themes.',
        'Strong burns. Occasional mild swears. Adult themes.',
        'R-rated. Full profanity. Adult humor. No holds barred.',
      ];
      
      const roasterLines = roasterPersonas.map((p) => `${p?.name} (Voice: ${p?.voice}, Style: ${p?.roastStyle})`).join('\n- ');
      
      const systemPrompt = `You are producing a Comedy Central-style roast script.

The characters are:
- HOST/MC: ${hostPersona?.name}
  Voice: ${hostPersona?.voice}
  Roast Style: ${hostPersona?.roastStyle}
  Catchphrase: ${hostPersona?.catchphrase}

- ROASTER: ${roasterLines}

- ROASTEE: ${roasteePersona?.name}
  Personality: ${roasteePersona?.personality}
  Roast Style: ${roasteePersona?.roastStyle}

PROFANITY LEVEL: ${profanity}
${profanityInstructions[profanity - 1]}

FORMAT REQUIREMENTS:
- Host opens with a 2-3 punchline intro
- Each Roaster delivers 2-4 burns targeting the Roastee
- Roastee fires back with 2-4 defensive burns
- Host closes with a classic sign-off
- Total script should be 400-600 words
- Write in actual character voices, not placeholders`;

      const response = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`,
        },
        body: JSON.stringify({
          model: 'gpt-4',
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: 'Write the roast script now. Be funny. Be in character. Make it actually funny - punchlines should have genuine shock/surprise.' },
          ],
          temperature: 0.9,
          max_tokens: 1500,
        }),
      });
      
      const data = await response.json();
      
      if (data.choices && data.choices[0]?.message?.content) {
        return NextResponse.json({
          script: data.choices[0].message.content + '\n\nGenerated by Humble Claw Roast Generator',
        });
      }
    }
    
    // Fallback to mock script
    const mockScript = SAMPLE_SCRIPTS[Math.floor(Math.random() * SAMPLE_SCRIPTS.length)];
    return NextResponse.json({ script: mockScript, mock: true });
    
  } catch (error) {
    console.error('Roast generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate roast. Please try again.' },
      { status: 500 }
    );
  }
}

export async function GET() {
  return NextResponse.json({ personas });
}
