import { useState, useCallback } from 'react';
import { BrowserRouter } from 'react-router-dom';
import Navigation from './components/Navigation';
import PersonaSelector from './components/PersonaSelector';
import ProfanitySlider from './components/ProfanitySlider';
import GenerateButton from './components/GenerateButton';
import RoastOutput from './components/RoastOutput';
import { PortraitGrid } from './components/CharacterPortrait';
import { personas, getPersonaBySlug } from './api/personas';
import './App.css';

const SAMPLE_SCRIPTS = [
`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎤 HOST: HULK HOGAN
"What is best in life? To watch your enemies burn. And that includes YOU, roastee."

👊 ROASTER 1: DARTH VADER
"Your lack of talent disturbs me."
"Every time you try something, you fail. Like your diet. Like your career. Like your hairline."
"I've seen more intimidating porgs than you."

👊 ROASTER 2: SPONGEBOB
"I'm ready! I'm ready! I'm ready to roast you!"
"You think jellyfishing is dangerous? Let me tell you about your life choices."
"Bikini Bottom would never accept someone this uncool."

🎯 ROASFEE: RIC FLAIR
"Y'all want 'WOOOOO'?! I'M the Nature Boy! You can't handle this!"
"I've been wrestling for 40 years and I've never seen such a mediocre performance!"
"Whoooo! That's right! I'M the real champion here, and these jabronis need to humble themselves!"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,

`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎤 HOST: THE UNDERTAKER
"Welcome to the graveyard of your dreams. I dig these roasts."

👊 ROASTER 1: MIKE TYSON
"Talk is cheap. But your talk is especially cheap. Like, alarmingly cheap."
"I've seen tougher cookies than you. And I ate them."

👊 ROASTER 2: ARNOLD SCHWARZENEGGER
"Let me tell you something. You? Not a champion. You couldn't carry my workout playlist."

🎯 ROASFEE: PETER GRIFFIN
"I've had better conversations with my beer bong than with you."
"My bird is smarter than you. And he's mentally challenged!"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,

`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎤 HOST: MACHO MAN
"Oooooh yeah! The crowd goes WILD for my roasting skills!"

👊 ROASTER 1: RIC FLAIR
"WOOOOO! Nature Boy style, baby! You couldn't match my excellence if you tried!"
"I've had better opponents in a warm-up than you!"

👊 ROASTER 2: THE UNDERTAKER
"Your comedy is as dead as my career. Oh wait, my career is VERY much alive."
"I've risen from the grave to roast you. That's how serious this is."

🎯 ROASFEE: SKELETON
"Bones? I got bones! Where's your roast game?!"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`
];

function App() {
  const [config, setConfig] = useState({
    host: null,
    roasters: [],
    roastee: null
  });
  const [profanity, setProfanity] = useState(3);
  const [generatePortraits, setGeneratePortraits] = useState(true);
  const [script, setScript] = useState(null);
  const [loading, setLoading] = useState(false);
  const [scriptIndex, setScriptIndex] = useState(0);

  const canGenerate = config.host && config.roasters.length > 0 && config.roastee;

  const handleGenerate = useCallback(async () => {
    if (!canGenerate) return;
    
    setLoading(true);
    setScript(null);
    
    // Simulate API call with fake loading
    await new Promise(resolve => setTimeout(resolve, 2500));
    
    // Cycle through sample scripts (in real app, this would be API call)
    const nextIndex = (scriptIndex + 1) % SAMPLE_SCRIPTS.length;
    setScriptIndex(nextIndex);
    setScript(SAMPLE_SCRIPTS[nextIndex]);
    setLoading(false);
  }, [canGenerate, scriptIndex]);

  const handleRegenerate = useCallback(() => {
    handleGenerate();
  }, [handleGenerate]);

  const handleCopy = useCallback(() => {
    if (script) {
      navigator.clipboard.writeText(script + '\n\n🔥 Generated by Humble Claw Roast Generator');
      alert('Roast copied to clipboard!');
    }
  }, [script]);

  const handleShare = useCallback(() => {
    const url = `${window.location.origin}/roast?host=${config.host}&roasters=${config.roasters.join(',')}&roastee=${config.roastee}&profanity=${profanity}`;
    navigator.clipboard.writeText(url);
    alert('Share link copied to clipboard!');
  }, [config, profanity]);

  const characters = [
    config.host ? { ...getPersonaBySlug(config.host), role: 'host' } : null,
    ...config.roasters.map(r => ({ ...getPersonaBySlug(r), role: 'roaster' })),
    config.roastee ? { ...getPersonaBySlug(config.roastee), role: 'roastee' } : null
  ].filter(Boolean);

  return (
    <BrowserRouter>
      <div className="app">
        <Navigation />
        
        <main className="main-content">
          <PersonaSelector config={config} onChange={setConfig} />
          
          <ProfanitySlider 
            value={profanity} 
            onChange={setProfanity}
          />
          
          <GenerateButton 
            onClick={handleGenerate}
            disabled={!canGenerate}
            loading={loading}
          />
          
          <RoastOutput
            script={script}
            loading={loading}
            onRegenerate={handleRegenerate}
            onCopy={handleCopy}
            onShare={handleShare}
          />
          
          {script && generatePortraits && (
            <PortraitGrid characters={characters} />
          )}
        </main>
        
        <footer className="footer">
          <p>🔥 Humble Claw Roast Generator — Built for chaos</p>
        </footer>
      </div>
    </BrowserRouter>
  );
}

export default App;
